# Generated by Django 5.2.10 on 2026-08-11 10:57

import apps.scheduling.models
import apps.scheduling.validators
import django.db.models.deletion
import django.db.models.functions.math
import django.db.models.lookups
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("start_minutes", models.PositiveSmallIntegerField(default=540)),
                ("end_minutes", models.PositiveSmallIntegerField(default=1020)),
                (
                    "slot_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[(15, "15 minutes"), (30, "30 minutes")], default=30
                    ),
                ),
                ("spans_next_day", models.BooleanField(default=False)),
                (
                    "days",
                    models.JSONField(default=apps.scheduling.models.default_weekdays),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("inperson", "In person"),
                            ("virtual", "Virtual"),
                            ("mixed", "Mixed"),
                        ],
                        default="inperson",
                        max_length=16,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                (
                    "participant_view_permission",
                    models.CharField(
                        choices=[
                            ("own_only", "Own only"),
                            ("all_after_submit", "All after submit"),
                            ("realtime", "Realtime"),
                        ],
                        default="own_only",
                        max_length=16,
                    ),
                ),
                (
                    "day_selection_type",
                    models.CharField(
                        choices=[
                            ("days_of_week", "Days of week"),
                            ("specific_dates", "Specific dates"),
                        ],
                        default="days_of_week",
                        max_length=16,
                    ),
                ),
                ("specific_dates", models.JSONField(blank=True, null=True)),
                ("response_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        max_length=64,
                        validators=[apps.scheduling.validators.validate_iana_timezone],
                    ),
                ),
                ("reminders_enabled", models.BooleanField(default=True)),
                ("reminder_hours_before", models.PositiveSmallIntegerField(default=24)),
                (
                    "access_mode",
                    models.CharField(
                        choices=[
                            ("invite_only", "Invite only"),
                            ("open_link", "Open link"),
                        ],
                        default="invite_only",
                        max_length=16,
                    ),
                ),
                (
                    "meeting_duration_minutes",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("results_revision", models.PositiveBigIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("finalized", "Finalized"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventDeletionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(unique=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("deleted_version", models.PositiveBigIntegerField()),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_deletion_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventDuplicationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("source_version", models.PositiveBigIntegerField()),
                (
                    "duplicate_event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_duplication_requests",
                        to="scheduling.event",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_duplication_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplication_requests",
                        to="scheduling.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "access_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("opened", "Opened"),
                            ("joined", "Joined"),
                            ("draft_saved", "Draft saved"),
                            ("submitted", "Submitted"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
                ("first_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("draft_saved_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("custom_message", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="scheduling.event",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_event_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="EventResultInvalidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_invalidations",
                        to="scheduling.event",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventResultSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_revision", models.PositiveBigIntegerField(default=1)),
                ("computed_revision", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("refreshing", "Refreshing"),
                            ("fresh", "Fresh"),
                            ("failed", "Failed"),
                        ],
                        default="refreshing",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_token", models.UUIDField(blank=True, null=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_snapshot",
                        to="scheduling.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "timezone",
                    models.CharField(
                        max_length=64,
                        validators=[apps.scheduling.validators.validate_iana_timezone],
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("inperson", "In person"), ("virtual", "Virtual")],
                        max_length=16,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                ("calendar_uid", models.CharField(max_length=255, unique=True)),
                ("calendar_sequence", models.PositiveIntegerField(default=0)),
                ("attendance_snapshot", models.JSONField(default=dict)),
                ("confirmed_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_final_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_meeting",
                        to="scheduling.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-confirmed_at"],
            },
        ),
        migrations.CreateModel(
            name="FinalizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("meeting_sequence", models.PositiveIntegerField()),
                ("resulting_event_version", models.PositiveBigIntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finalization_requests",
                        to="scheduling.event",
                    ),
                ),
                (
                    "final_meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation_requests",
                        to="scheduling.finalmeeting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("participant_name", models.CharField(max_length=100)),
                ("availability_inperson", models.JSONField(default=list)),
                ("availability_virtual", models.JSONField(default=list)),
                ("submitted", models.BooleanField(default=False)),
                ("first_draft_saved_at", models.DateTimeField(blank=True, null=True)),
                ("first_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("last_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("hidden", models.BooleanField(default=False)),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="scheduling.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterBulkUpdateReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("results_revision", models.PositiveBigIntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_bulk_update_receipts",
                        to="scheduling.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RosterImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV upload"),
                            ("xlsx", "Excel upload"),
                            ("paste", "Pasted table"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("committing", "Committing"),
                            ("committed", "Committed"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="preview",
                        max_length=16,
                    ),
                ),
                ("worksheets", models.JSONField(default=list)),
                (
                    "selected_worksheet",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("header_row", models.PositiveIntegerField(default=1)),
                ("column_mapping", models.JSONField(default=dict)),
                ("defaults", models.JSONField(default=dict)),
                ("summary", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField()),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_import_batches",
                        to="scheduling.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterImportReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "mode",
                    models.CharField(
                        choices=[("merge", "Merge"), ("rebuild", "Rebuild")],
                        max_length=16,
                    ),
                ),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("results_revision", models.PositiveBigIntegerField()),
                (
                    "committed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="scheduling.rosterimportbatch",
                    ),
                ),
                (
                    "committed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_import_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_import_receipts",
                        to="scheduling.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-committed_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worksheet", models.CharField(max_length=128)),
                ("row_number", models.PositiveIntegerField()),
                ("raw_values", models.JSONField(default=list)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "group_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("included", models.BooleanField(default=True)),
                ("selected", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(default=list)),
                (
                    "duplicate_status",
                    models.CharField(
                        choices=[
                            ("unique", "Unique"),
                            ("identical", "Identical duplicate"),
                            ("conflict", "Conflicting duplicate"),
                        ],
                        default="unique",
                        max_length=16,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="scheduling.rosterimportbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["worksheet", "row_number"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_identifier", models.UUIDField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("self", "Participant"),
                            ("organizer", "Organizer"),
                            ("import", "Import"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submit", "Submit"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=16,
                    ),
                ),
                ("participant_version", models.PositiveBigIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_edit_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_edit_records",
                        to="scheduling.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_edit_records",
                        to="scheduling.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryEventSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_sessions",
                        to="scheduling.eventinvitation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_event_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_sessions",
                        to="scheduling.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("organizer", "Organizer"),
                            ("participant", "Participant"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_events",
                        to="scheduling.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.FloatField(default=1.0)),
                ("included", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="scheduling.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="scheduling.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["participant__participant_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "open", "finalized", "closed", "archived"])
                ),
                name="event_status_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="event_version_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_minutes__gte", 0), ("start_minutes__lt", 1440)
                ),
                name="event_start_minutes_in_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_minutes__gte", 0), ("end_minutes__lt", 1440)),
                name="event_end_minutes_in_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("spans_next_day", True),
                        ("end_minutes__lte", models.F("start_minutes")),
                    ),
                    models.Q(
                        ("spans_next_day", False),
                        ("end_minutes__gt", models.F("start_minutes")),
                    ),
                    _connector="OR",
                ),
                name="event_window_direction_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_minutes__in", [15, 30])),
                name="event_slot_minutes_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("access_mode__in", ["invite_only", "open_link"])),
                name="event_access_mode_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("meeting_duration_minutes__gte", 15),
                    ("meeting_duration_minutes__lte", 480),
                ),
                name="event_meeting_duration_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    django.db.models.functions.math.Mod(
                        models.F("meeting_duration_minutes"), models.F("slot_minutes")
                    ),
                    0,
                ),
                name="event_meeting_duration_aligns_to_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("results_revision__gte", 1)),
                name="event_results_revision_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventdeletionrecord",
            constraint=models.UniqueConstraint(
                fields=("organizer", "idempotency_key"),
                name="one_event_deletion_per_member_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventdeletionrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("deleted_version__gte", 1)),
                name="event_deletion_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventduplicationrequest",
            constraint=models.UniqueConstraint(
                fields=("source_event", "idempotency_key"),
                name="one_event_duplication_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventduplicationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_version__gte", 1)),
                name="event_duplication_source_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(fields=["email"], name="scheduling__email_39f572_idx"),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(fields=["status"], name="scheduling__status_7dc7be_idx"),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(
                fields=["first_sent_at"], name="scheduling__first_s_90998e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(
                fields=["last_sent_at"], name="scheduling__last_se_af9ba0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(
                fields=["reminder_sent_at"], name="scheduling__reminde_f174ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinvitation",
            constraint=models.UniqueConstraint(
                fields=("event", "email"), name="one_invitation_per_event_email"
            ),
        ),
        migrations.AddIndex(
            model_name="eventresultinvalidation",
            index=models.Index(
                fields=["event", "processed_at", "created_at"],
                name="result_inval_event_pending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventresultsnapshot",
            index=models.Index(
                fields=["status", "updated_at"], name="scheduling__status_0d72ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventresultsnapshot",
            index=models.Index(
                fields=["locked_at"], name="scheduling__locked__621935_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventresultsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_revision__gte", 0)),
                name="result_snapshot_requested_revision_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventresultsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("computed_revision__gte", 0)),
                name="result_snapshot_computed_revision_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="finalmeeting",
            index=models.Index(
                fields=["active", "starts_at"], name="scheduling__active_0364d7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="finalmeeting",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="final_meeting_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalizationrequest",
            constraint=models.UniqueConstraint(
                fields=("event", "idempotency_key"),
                name="one_finalization_request_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="finalizationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("resulting_event_version__gte", 1)),
                name="finalization_event_version_is_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["event", "submitted"], name="scheduling__event_i_a24ab8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["first_submitted_at"], name="scheduling__first_s_690e52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("event", "member"), name="one_participant_per_member_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="participant_version_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterbulkupdatereceipt",
            constraint=models.UniqueConstraint(
                fields=("event", "idempotency_key"),
                name="one_roster_bulk_update_receipt_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterbulkupdatereceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("results_revision__gte", 1)),
                name="roster_bulk_receipt_revision_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="rosterimportbatch",
            index=models.Index(
                fields=["event", "status", "created_at"],
                name="scheduling__event_i_2e05f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rosterimportbatch",
            index=models.Index(
                fields=["status", "expires_at"], name="scheduling__status_b3896c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterimportreceipt",
            constraint=models.UniqueConstraint(
                fields=("event", "idempotency_key"),
                name="one_roster_import_receipt_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterimportreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("results_revision__gte", 1)),
                name="roster_receipt_results_revision_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="rosterimportrow",
            index=models.Index(
                fields=["batch", "worksheet", "row_number"],
                name="scheduling__batch_i_ae075a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rosterimportrow",
            index=models.Index(
                fields=["batch", "selected", "duplicate_status"],
                name="scheduling__batch_i_a47c58_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterimportrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "worksheet", "row_number"),
                name="one_roster_import_row_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterimportrow",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0.0), ("weight__lte", 1.0)),
                name="roster_import_weight_in_range",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleeditrecord",
            index=models.Index(
                fields=["event", "created_at"], name="scheduling__event_i_f61be9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleeditrecord",
            index=models.Index(
                fields=["participant", "created_at"],
                name="scheduling__partici_2a0f9b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleeditrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("participant_version__gte", 1)),
                name="schedule_edit_participant_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="temporaryeventsession",
            index=models.Index(
                fields=["member", "revoked_at", "expires_at"],
                name="tmp_session_member_exp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="temporaryeventsession",
            index=models.Index(
                fields=["participant", "revoked_at", "expires_at"],
                name="tmp_session_part_exp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="temporaryeventsession",
            index=models.Index(fields=["expires_at"], name="tmp_session_expires_idx"),
        ),
        migrations.AddConstraint(
            model_name="userevent",
            constraint=models.UniqueConstraint(
                fields=("member", "event", "role"), name="one_user_event_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="weight",
            constraint=models.UniqueConstraint(
                fields=("event", "participant"), name="one_weight_per_event_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="weight",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0.0), ("weight__lte", 1.0)),
                name="weight_between_zero_and_one",
            ),
        ),
    ]
