# Generated by Django 6.1 on 2026-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0003_alter_rosterimportreceipt_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="participant",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="participant",
            name="organizer_managed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="rosterimportrow",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
