# Generated by Django 6.1 on 2026-09-22 03:52

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

RESEED_CHUNK_SIZE = 500


def _is_untouched_schedule(values, starting_value) -> bool:
    return bool(values) and all(value == starting_value for value in values)


def _reseed_untouched_participants(apps, schema_editor, *, old_value, new_value):
    """Move people who never painted from one starting schedule to the other.

    Only participants who never saved a draft or submitted, and whose arrays are still
    entirely ``old_value``, are rewritten to ``new_value``. Anyone who ever saved a draft or
    submitted is left alone: under the old "paint what works" rules an all-busy saved
    response meant "nothing works", not "I have not looked yet".
    """
    Participant = apps.get_model("scheduling", "Participant")
    now = timezone.now()
    pending = []

    def flush():
        if pending:
            Participant.objects.using(schema_editor.connection.alias).bulk_update(
                pending,
                ["availability_inperson", "availability_virtual", "version", "updated_at"],
            )
            pending.clear()

    participants = (
        Participant.objects.using(schema_editor.connection.alias)
        .filter(
            submitted=False,
            first_draft_saved_at__isnull=True,
            first_submitted_at__isnull=True,
        )
        .only("id", "availability_inperson", "availability_virtual", "version", "updated_at")
        .iterator(chunk_size=RESEED_CHUNK_SIZE)
    )
    for participant in participants:
        if not _is_untouched_schedule(participant.availability_inperson, old_value):
            continue
        if not _is_untouched_schedule(participant.availability_virtual, old_value):
            continue
        participant.availability_inperson = [new_value] * len(participant.availability_inperson)
        participant.availability_virtual = [new_value] * len(participant.availability_virtual)
        participant.version += 1
        participant.updated_at = now
        pending.append(participant)
        if len(pending) >= RESEED_CHUNK_SIZE:
            flush()
    flush()


def reseed_untouched_participants_to_available(apps, schema_editor):
    """Before this migration everyone started all-busy; events now default to available."""
    _reseed_untouched_participants(apps, schema_editor, old_value=0, new_value=1)


def reseed_untouched_participants_to_busy(apps, schema_editor):
    """Rolling back restores the all-busy start for people who still never painted."""
    _reseed_untouched_participants(apps, schema_editor, old_value=1, new_value=0)


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0003_alter_rosterimportreceipt_batch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="starting_availability",
            field=models.CharField(
                choices=[("available", "Available"), ("busy", "Busy")],
                default="available",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("starting_availability__in", ["available", "busy"])),
                name="event_starting_availability_is_valid",
            ),
        ),
        migrations.RunPython(
            reseed_untouched_participants_to_available,
            reseed_untouched_participants_to_busy,
        ),
    ]
