# Generated by Django 6.1 on 2026-09-22 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0004_event_starting_availability"),
        ("scheduling", "0004_participant_contact_fields"),
    ]

    operations = []
