# Generated by Django 6.1 on 2026-09-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0007_participantgroup_multi_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="response_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
