"""Configured size limits for roster imports."""

from django.conf import settings

MAX_UPLOAD_BYTES = settings.ROSTER_IMPORT_MAX_FILE_BYTES
MAX_UNCOMPRESSED_BYTES = settings.ROSTER_IMPORT_MAX_UNCOMPRESSED_BYTES
MAX_COLUMNS = settings.ROSTER_IMPORT_MAX_COLUMNS
MAX_ROSTER_ROWS = settings.ROSTER_IMPORT_MAX_ROWS
MAX_PREVIEW_ROWS = MAX_ROSTER_ROWS * 5
PREVIEW_LIFETIME = settings.ROSTER_IMPORT_PREVIEW_LIFETIME
