# Generated by Django 5.2.10 on 2026-07-08 06:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("start_hour", models.PositiveSmallIntegerField(default=9)),
                ("end_hour", models.PositiveSmallIntegerField(default=17)),
                ("days", models.JSONField(default=list)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("inperson", "In person"),
                            ("virtual", "Virtual"),
                            ("mixed", "Mixed"),
                        ],
                        default="inperson",
                        max_length=16,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                (
                    "participant_view_permission",
                    models.CharField(
                        choices=[
                            ("own_only", "Own only"),
                            ("all", "All after submit"),
                            ("realtime", "Realtime"),
                        ],
                        default="own_only",
                        max_length=16,
                    ),
                ),
                (
                    "day_selection_type",
                    models.CharField(
                        choices=[
                            ("days_of_week", "Days of week"),
                            ("specific_dates", "Specific dates"),
                        ],
                        default="days_of_week",
                        max_length=16,
                    ),
                ),
                ("specific_dates", models.JSONField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("participant_name", models.CharField(max_length=100)),
                ("schedule_inperson", models.TextField()),
                ("schedule_virtual", models.TextField()),
                ("submitted", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="scheduling.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("organizer", "Organizer"),
                            ("participant", "Participant"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_events",
                        to="scheduling.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.FloatField(default=1.0)),
                ("included", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="scheduling.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="scheduling.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["participant__participant_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("event", "member"), name="one_participant_per_member_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="userevent",
            constraint=models.UniqueConstraint(
                fields=("member", "event", "role"), name="one_user_event_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="weight",
            constraint=models.UniqueConstraint(
                fields=("event", "participant"), name="one_weight_per_event_participant"
            ),
        ),
    ]
