// Central icon vocabulary for Releviz.
//
// Every icon comes from Bootstrap Icons (via react-icons/bs) so the interface
// uses one consistent set. Import the semantic names below instead of picking
// glyphs ad hoc; icons are decorative and must be paired with a text label.
export {
  BsPlusLg as AddIcon,
  BsArchive as ArchiveIcon,
  BsArrowRight as ArrowRightIcon,
  BsArrowUpCircle as UpgradeIcon,
  BsBarChartFill as ResultsIcon,
  BsBoxArrowInRight as SignInIcon,
  BsBoxArrowRight as SignOutIcon,
  BsBoxArrowUpRight as OpenIcon,
  BsCalendarCheck as CalendarCheckIcon,
  BsCalendar3 as CalendarIcon,
  BsCameraVideo as VirtualIcon,
  BsCardChecklist as RosterIcon,
  BsCheckCircleFill as SuccessIcon,
  BsCheckLg as CheckIcon,
  BsChevronDown as ChevronDownIcon,
  BsChevronLeft as ChevronLeftIcon,
  BsChevronRight as ChevronRightIcon,
  BsChevronUp as ChevronUpIcon,
  BsClock as ClockIcon,
  BsCopy as CopyIcon,
  BsDownload as DownloadIcon,
  BsEnvelope as EmailIcon,
  BsExclamationTriangleFill as WarningIcon,
  BsXCircleFill as ErrorIcon,
  BsFileEarmarkSpreadsheet as SpreadsheetIcon,
  BsFlagFill as FinalizeIcon,
  BsFloppy as SaveIcon,
  BsFunnel as FilterIcon,
  BsGear as SettingsIcon,
  BsGeoAlt as LocationIcon,
  BsGlobe2 as TimezoneIcon,
  BsGrid1X2 as DashboardIcon,
  BsHourglassSplit as PendingIcon,
  BsInfoCircleFill as InfoIcon,
  BsLink45Deg as LinkIcon,
  BsLock as LockIcon,
  BsPatchCheck as VerifiedIcon,
  BsPencil as EditIcon,
  BsPeople as GroupIcon,
  BsPersonCircle as AccountIcon,
  BsPersonPlus as InviteIcon,
  BsArrowClockwise as RefreshIcon,
  BsSearch as SearchIcon,
  BsSend as SendIcon,
  BsSliders as TuneIcon,
  BsTrash3 as DeleteIcon,
  BsTrophy as BestIcon,
  BsUpload as ImportIcon,
  BsXLg as CloseIcon,
  BsEye as ViewIcon,
  BsBell as ReminderIcon,
  BsListCheck as TasksIcon,
  BsShieldLock as SecurityIcon,
  BsCircleHalf as PartialIcon,
  BsCheck2 as AvailableIcon,
  BsSlashCircle as BusyIcon,
} from "react-icons/bs";
