# Generated by Django 5.2.10 on 2026-07-08 06:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.authn.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSAKeypair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(default="site-encryption", max_length=255)),
                ("public_key_pem", models.TextField(blank=True)),
                ("private_key_pem", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("profile_image", models.URLField(blank=True, default="")),
                ("admin_apps", models.JSONField(blank=True, default=list)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "date_joined"],
            },
            managers=[
                ("objects", apps.authn.managers.MemberManager()),
            ],
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=32,
                    ),
                ),
                ("subscribe", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email_address"], name="authn_conta_email_a_6f580e_idx"),
                    models.Index(fields=["email_type"], name="authn_conta_email_t_8a1be3_idx"),
                    models.Index(fields=["verified"], name="authn_conta_verifie_dff1e7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("email_type", "primary")),
                        fields=("member",),
                        name="one_primary_email_per_member",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("region", models.CharField(default="1-US", max_length=20)),
                ("subscribe", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_phones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["phone_number"], name="authn_conta_phone_n_a8a545_idx"),
                    models.Index(fields=["region"], name="authn_conta_region_9e701d_idx"),
                    models.Index(fields=["verified"], name="authn_conta_verifie_626d50_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailAuthChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("login", "Login"),
                            ("password_reset", "Password Reset"),
                            ("password_change", "Password Change"),
                            ("account_delete", "Account Delete"),
                            ("contact_email_verify", "Contact Email Verify"),
                            ("admin_login", "Admin Login"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        default="email",
                        max_length=8,
                    ),
                ),
                (
                    "target_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "target_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("code_hash", models.CharField(max_length=255)),
                (
                    "verification_token_hash",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_auth_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "target_email", "status"],
                        name="authn_email_purpose_dcb13a_idx",
                    ),
                    models.Index(
                        fields=["member", "purpose", "status"],
                        name="authn_email_member__7cb12d_idx",
                    ),
                    models.Index(fields=["expires_at"], name="authn_email_expires_8e33bc_idx"),
                ],
            },
        ),
    ]
