# Generated by Django 6.1 on 2026-08-19 20:05

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.authn.models.members.manager
import apps.authn.models.security.impersonation_token


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "admin_apps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Django apps this admin may manage (e.g. ["cms", "event"]). Superusers ignore this.',
                        verbose_name="Admin apps",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, help_text="Middle Name", max_length=255, null=True
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("full", "Full"), ("temporary", "Temporary")],
                        db_index=True,
                        default="full",
                        help_text="Whether this member has a full account or event-scoped temporary access.",
                        max_length=16,
                    ),
                ),
                (
                    "profile_image",
                    models.TextField(
                        blank=True,
                        help_text="Profile image, base64-encoded.",
                        null=True,
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", apps.authn.models.members.manager.MemberManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.CharField(db_index=True, editable=False, max_length=64, unique=True),
                ),
                (
                    "role",
                    models.CharField(choices=[("admin", "Admin")], default="admin", max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional note included in the invitation email.",
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Invitation",
                "verbose_name_plural": "Admin Invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(max_length=64)),
                ("key_hash", models.CharField(max_length=64)),
                ("request_count", models.PositiveIntegerField(default=0)),
                (
                    "window_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "blocked_until"],
                        name="authn_authr_scope_ce5d62_idx",
                    ),
                    models.Index(fields=["updated_at"], name="authn_authr_updated_308110_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_hash"),
                        name="unique_auth_rate_limit_bucket",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImpersonationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "token",
                    models.CharField(db_index=True, editable=False, max_length=128, unique=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.authn.models.security.impersonation_token.default_expiry
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The admin who initiated the impersonation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_tokens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The member being impersonated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RSAKeypair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "key_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Key identifier (UUID).",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="site-signing",
                        help_text="label for this keypair.",
                        max_length=255,
                    ),
                ),
                (
                    "public_key_pem",
                    models.TextField(blank=True, help_text="Public key in PEM format."),
                ),
                (
                    "private_key_pem",
                    models.TextField(blank=True, help_text="Private key in PEM format."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this keypair is currently active.",
                    ),
                ),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RSA Keypair",
                "verbose_name_plural": "RSA Keypairs",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("name",),
                        name="authn_one_active_rsa_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Email address for contact",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        help_text="Type of email address",
                        max_length=255,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "subscribe",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the email is subscribed to communications",
                        verbose_name="Subscribed",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email address has been verified",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member this email belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Email",
                "verbose_name_plural": "Contact Emails",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email_address"], name="authn_conta_email_a_6f580e_idx"),
                    models.Index(fields=["email_type"], name="authn_conta_email_t_8a1be3_idx"),
                    models.Index(fields=["verified"], name="authn_conta_verifie_dff1e7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email_address"),
                        name="unique_contact_email_ci",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("email_type", "primary")),
                        fields=("member",),
                        name="one_primary_email_per_member",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailAuthChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("login", "Login"),
                            ("password_reset", "Password Reset"),
                            ("password_change", "Password Change"),
                            ("account_delete", "Account Delete"),
                            ("contact_email_verify", "Contact Email Verify"),
                            ("admin_login", "Admin Login"),
                            ("temp_event_access", "Temp Event Access"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email address where the verification code was sent.",
                        max_length=254,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hashed verification code.",
                        max_length=255,
                    ),
                ),
                (
                    "verification_token_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hashed token returned after a code is verified.",
                        max_length=255,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the code or verification token expires."),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the verification code was successfully checked.",
                        null=True,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the code email was sent.",
                        null=True,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_auth_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "target_email", "status"],
                        name="authn_email_purpose_dcb13a_idx",
                    ),
                    models.Index(
                        fields=["member", "purpose", "status"],
                        name="authn_email_member__7cb12d_idx",
                    ),
                    models.Index(fields=["expires_at"], name="authn_email_expires_8e33bc_idx"),
                ],
            },
        ),
    ]
