# Generated by Django 6.0.8 on 2026-08-11 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="member",
            name="title",
        ),
    ]
