# Generated by Django 6.0.8 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0002_remove_member_organization_remove_member_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="access_level",
            field=models.CharField(
                choices=[("full", "Full"), ("temporary", "Temporary")],
                db_index=True,
                default="full",
                help_text=(
                    "Whether this member has a full account or event-scoped temporary access."
                ),
                max_length=16,
            ),
        ),
    ]
