# Generated by Django 6.0.8 on 2026-08-18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authn", "0003_member_access_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(max_length=64)),
                ("key_hash", models.CharField(max_length=64)),
                ("request_count", models.PositiveIntegerField(default=0)),
                (
                    "window_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "blocked_until"],
                        name="authn_authr_scope_ce5d62_idx",
                    ),
                    models.Index(
                        fields=["updated_at"],
                        name="authn_authr_updated_308110_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_hash"),
                        name="unique_auth_rate_limit_bucket",
                    )
                ],
            },
        ),
    ]
