# Generated by Django 6.1 on 2026-08-19 20:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32, unique=True)),
                (
                    "next_available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivery Rate Limit",
                "verbose_name_plural": "Delivery Rate Limits",
            },
        ),
        migrations.CreateModel(
            name="SiteMaintenanceControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_maintenance",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to put the site into maintenance mode.",
                        verbose_name="Maintenance Mode",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="We are performing scheduled maintenance. Please try again shortly.",
                        help_text="Message displayed to users during maintenance.",
                        verbose_name="Maintenance Message",
                    ),
                ),
                (
                    "bypass_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Password that allows authorized users to bypass maintenance mode. Leave blank to disable bypass.",
                        max_length=128,
                        verbose_name="Bypass Password",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Maintenance Control",
                "verbose_name_plural": "Site Maintenance Control",
            },
        ),
        migrations.CreateModel(
            name="AWSCredentialConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="A label to identify this configuration (e.g. 'Production IAM', 'Dev Account').",
                        max_length=128,
                        verbose_name="Config Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active. Activating this will deactivate others.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "access_key_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS IAM access key ID (starts with AKIA…). Shared by SES and Bedrock.",
                        max_length=128,
                        verbose_name="Access Key ID",
                    ),
                ),
                (
                    "encrypted_secret_access_key",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AWS IAM secret access key, encrypted at rest with Fernet.",
                        verbose_name="Encrypted Secret Access Key",
                    ),
                ),
                (
                    "default_region",
                    models.CharField(
                        blank=True,
                        default="us-west-2",
                        help_text="AWS region used by SES and Bedrock.",
                        max_length=32,
                        verbose_name="AWS Region",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AWS Credential",
                "verbose_name_plural": "AWS Credentials",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="core_one_active_aws_config",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("kind", models.CharField(db_index=True, max_length=80)),
                ("dedupe_key", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("retry", "Retry scheduled"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("uncertain", "Uncertain delivery"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "claim_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "provider_call_started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "can_retry_after_claim",
                    models.BooleanField(
                        default=True,
                        help_text="Whether a stale claimed job is safe to retry. Disable for provider deliveries whose outcome cannot be queried idempotently.",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", editable=False),
                ),
            ],
            options={
                "ordering": ["available_at", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "available_at", "created_at"],
                        name="core_job_claim_idx",
                    ),
                    models.Index(
                        fields=["status", "claimed_at"], name="core_job_stale_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "dedupe_key"),
                        name="unique_background_job_dedupe_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedbackSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("problem", "Problem"),
                            ("idea", "Idea"),
                            ("usability", "Usability"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(max_length=5000)),
                ("page_path", models.CharField(blank=True, default="", max_length=500)),
                ("consent_to_follow_up", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("request_id", models.UUIDField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Submission",
                "verbose_name_plural": "Feedback Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_feedba_status_f46ee2_idx",
                    ),
                    models.Index(
                        fields=["category", "created_at"],
                        name="core_feedba_categor_706aef_idx",
                    ),
                    models.Index(
                        fields=["member", "created_at"],
                        name="core_feedba_member__f19642_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("category__in", ["problem", "idea", "usability", "other"])
                        ),
                        name="feedback_category_is_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["new", "reviewing", "resolved"])
                        ),
                        name="feedback_status_is_valid",
                    ),
                ],
            },
        ),
    ]
