# Generated by Django 6.1 on 2026-09-18 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_feedbacksubmission"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedbacksubmission",
            name="core_feedba_status_f46ee2_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedbacksubmission",
            name="core_feedba_categor_706aef_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedbacksubmission",
            name="core_feedba_member__f19642_idx",
        ),
        migrations.RemoveConstraint(
            model_name="feedbacksubmission",
            name="feedback_category_is_valid",
        ),
        migrations.RemoveConstraint(
            model_name="feedbacksubmission",
            name="feedback_status_is_valid",
        ),
        migrations.DeleteModel(
            name="FeedbackSubmission",
        ),
    ]
