# Generated by Django 5.2

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_active_config_invariants"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32, unique=True)),
                (
                    "next_available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivery Rate Limit",
                "verbose_name_plural": "Delivery Rate Limits",
            },
        ),
    ]
