# Generated by Django 6.1 on 2026-08-19 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authn", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Default", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "from_email",
                    models.EmailField(
                        help_text="Verified SES sender address (e.g. noreply@example.com).",
                        max_length=254,
                        verbose_name="From Email",
                    ),
                ),
                (
                    "reply_to_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Optional reply-to address for outgoing emails.",
                        max_length=254,
                        verbose_name="Reply-To Email",
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-is_active", "name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("verification", "Verification"),
                            ("welcome", "Welcome"),
                            ("login_alert", "Login Alert"),
                            ("invitation", "Invitation"),
                            ("reminder", "Reminder"),
                            ("final_confirmation", "Final Confirmation"),
                            ("final_cancellation", "Final Cancellation"),
                            ("test", "Test"),
                        ],
                        max_length=32,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("html_body", models.TextField(blank=True, default="")),
                ("content_encrypted", models.BooleanField(default=False)),
                ("attachments", models.JSONField(default=list)),
                ("message_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("retry", "Retry"),
                            ("sent", "Sent"),
                            ("permanent_failure", "Permanent Failure"),
                            ("uncertain", "Uncertain Delivery"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_token", models.UUIDField(blank=True, null=True)),
                (
                    "provider_call_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "auth_challenge",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_job",
                        to="authn.emailauthchallenge",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_delivery_jobs",
                        to="scheduling.event",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_delivery_jobs",
                        to="scheduling.eventinvitation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_delivery_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_attempt_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("invitation", "Invitation"),
                            ("reminder", "Reminder"),
                            ("final_confirmation", "Final confirmation"),
                            ("final_cancellation", "Final cancellation"),
                        ],
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("created_job_count", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_delivery_requests",
                        to="scheduling.event",
                    ),
                ),
                (
                    "jobs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="delivery_requests",
                        to="mail.emaildeliveryjob",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_delivery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("verification", "Verification"),
                            ("welcome", "Welcome"),
                            ("login_alert", "Login Alert"),
                            ("invitation", "Invitation"),
                            ("reminder", "Reminder"),
                            ("final_confirmation", "Final Confirmation"),
                            ("final_cancellation", "Final Cancellation"),
                            ("test", "Test"),
                        ],
                        max_length=32,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=16
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "delivery_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="mail.emaildeliveryjob",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="scheduling.event",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="scheduling.eventinvitation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emaildeliveryjob",
            index=models.Index(
                fields=["status", "next_attempt_at"],
                name="mail_emaild_status_b5331e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryjob",
            index=models.Index(
                fields=["event", "message_type"], name="mail_emaild_event_i_1f685a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryjob",
            index=models.Index(
                fields=["member", "message_type"], name="mail_emaild_member__a4db00_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliveryjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)),
                name="email_job_max_attempts_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliveryjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("event__isnull", False), ("member__isnull", False), _connector="OR"
                ),
                name="email_job_has_domain_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryrequest",
            index=models.Index(
                fields=["event", "operation", "created_at"],
                name="mail_emaild_event_i_110c3f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliveryrequest",
            constraint=models.UniqueConstraint(
                fields=("event", "operation", "idempotency_key"),
                name="one_email_delivery_request_per_key",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessagelog",
            index=models.Index(
                fields=["message_type", "status"], name="mail_emailm_message_c4aaf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessagelog",
            index=models.Index(
                fields=["recipient"], name="mail_emailm_recipie_85e8b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessagelog",
            index=models.Index(
                fields=["created_at"], name="mail_emailm_created_aaaeec_idx"
            ),
        ),
    ]
