# Generated by Django 6.0.8 on 2026-08-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildeliveryjob",
            name="provider_call_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emaildeliveryjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("retry", "Retry"),
                    ("sent", "Sent"),
                    ("permanent_failure", "Permanent Failure"),
                    ("uncertain", "Uncertain Delivery"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
    ]
